/** Arabic auth strings — aligned with front/src/locales/ar.json (auth.*). */
export const authCopy = {
  brandName: 'Madar ERP',
  heroTagline: 'إدارة المبيعات والمخزون والمالية من مساحة عمل موحّدة.',
  heroSecureNote: 'دخول آمن — بياناتك محمية.',
  loginHeading: 'مرحبًا بعودتك',
  loginSubheading: 'سجّل الدخول إلى مساحة عمل مدار.',
  tenantId: 'مساحة العمل',
  tenantIdPlaceholder: 'معرف المنشأة',
  tenantHint: 'استخدم المعرف المخصص لمنشأتك.',
  email: 'البريد الإلكتروني',
  emailPlaceholder: 'أدخل البريد الإلكتروني',
  emailRequired: 'البريد الإلكتروني مطلوب',
  emailInvalid: 'البريد الإلكتروني غير صحيح',
  password: 'كلمة المرور',
  passwordPlaceholder: 'أدخل كلمة المرور',
  passwordRequired: 'كلمة المرور مطلوبة',
  passwordMinLength: 'كلمة المرور يجب أن تكون 6 أحرف على الأقل',
  signIn: 'متابعة إلى مساحة العمل',
  loginSuccess: 'تم تسجيل الدخول بنجاح',
  developedBy: 'Developed by',
  developerName: 'madar',
} as const;
