import type { ReportDefinition, ReportGroupId, ReportHubItem, ReportId } from './types';
import { extractArrayFromEnvelope, reportRows, reportSummary } from '@/utils/reportNormalizers';

const productReturnFields = [
  { key: 'returned_quantity', label: 'الكمية المرتجعة', format: 'number' as const },
  { key: 'returned_amount', label: 'قيمة المرتجعات', format: 'money' as const, primary: true },
  { key: 'return_count', label: 'عدد العمليات', format: 'number' as const },
  { key: 'category_name', label: 'التصنيف', format: 'text' as const },
  { key: 'latest_return_at', label: 'آخر مرتجع', format: 'date' as const },
];

export const REPORT_GROUPS: { id: ReportGroupId; title: string }[] = [
  { id: 'sales', title: 'المبيعات' },
  { id: 'inventory', title: 'المخزون' },
  { id: 'purchases', title: 'المشتريات' },
  { id: 'customers', title: 'العملاء' },
  { id: 'suppliers', title: 'الموردون' },
  { id: 'finance', title: 'المالية' },
  { id: 'marketing', title: 'التسويق' },
  { id: 'operations', title: 'التشغيل' },
  { id: 'other', title: 'أخرى' },
];

export const REPORT_DEFINITIONS: ReportDefinition[] = [
  {
    id: 'sales-dashboard',
    title: 'لوحة المبيعات',
    description: 'إيرادات يومية، أفضل المنتجات، وملخص المبيعات',
    group: 'sales',
    icon: 'dashboard',
    webRoute: '/reports/sales/dashboard',
    permission: 'view_reports',
    apiMethod: 'salesDashboard',
    filters: ['dateRange', 'branch'],
    exportSupported: true,
    exportType: 'sales',
    chart: { sectionId: 'daily', labelKey: 'date', valueKey: 'revenue', valueFormat: 'money' },
    metrics: [
      { key: 'orders_count', label: 'عدد الطلبات', format: 'number', tone: 'info' },
      { key: 'total_revenue', label: 'إجمالي الإيراد', format: 'money', tone: 'primary' },
      { key: 'total_paid', label: 'إجمالي المدفوع', format: 'money', tone: 'success' },
    ],
    sections: [
      {
        id: 'daily',
        title: 'الإيراد اليومي',
        extractRows: (p) => reportRows(p, ['daily_revenue']),
        fields: [
          { key: 'date', label: 'التاريخ', format: 'text', primary: true },
          { key: 'revenue', label: 'الإيراد', format: 'money' },
        ],
      },
      {
        id: 'top-products',
        title: 'أفضل المنتجات',
        extractRows: (p) => reportRows(p, ['top_products']),
        fields: [
          { key: 'product_name', label: 'المنتج', format: 'text', primary: true },
          { key: 'revenue', label: 'الإيراد', format: 'money' },
          { key: 'quantity', label: 'الكمية', format: 'number' },
        ],
      },
      {
        id: 'payments',
        title: 'توزيع الدفع',
        extractRows: (p) => {
          const summary = reportSummary(p);
          const nested = summary.sales_summary as Record<string, unknown> | undefined;
          return reportRows(nested ?? summary, ['payment_breakdown']);
        },
        fields: [
          { key: 'payment_type', label: 'طريقة الدفع', format: 'text', primary: true },
          { key: 'amount', label: 'المبلغ', format: 'money' },
        ],
      },
    ],
  },
  {
    id: 'sales-refunds',
    title: 'تقرير المرتجعات',
    description: 'ملخص المرتجعات وتفاصيلها حسب الفترة',
    group: 'sales',
    icon: 'replay',
    webRoute: '/reports/sales/refunds',
    permission: 'view_reports',
    apiMethod: 'refunds',
    filters: ['dateRange'],
    metrics: [
      { key: 'total_refunds', label: 'إجمالي المرتجعات', format: 'money', tone: 'danger' },
      { key: 'count', label: 'عدد المرتجعات', format: 'number', tone: 'info' },
      { key: 'average', label: 'متوسط المرتجع', format: 'money', tone: 'warning' },
    ],
    sections: [
      {
        id: 'refunds',
        title: 'تفاصيل المرتجعات',
        extractRows: (p) => reportRows(p, ['refunds', 'items']),
        fields: [
          { key: 'invoice_number', label: 'الفاتورة', format: 'text', primary: true },
          { key: 'amount', label: 'المبلغ', format: 'money' },
          { key: 'reason', label: 'السبب', format: 'text' },
          { key: 'status', label: 'الحالة', format: 'badge' },
          { key: 'created_at', label: 'التاريخ', format: 'date' },
        ],
      },
    ],
  },
  {
    id: 'sales-returns-by-product',
    title: 'مرتجعات بيع بالمنتج',
    description: 'كميات وقيم المرتجعات مجمعة حسب المنتج',
    group: 'sales',
    icon: 'inventory-2',
    webRoute: '/reports/sales-returns-by-product',
    permission: 'view_reports',
    apiMethod: 'salesReturnsByProduct',
    filters: ['dateRange', 'branch', 'category', 'product', 'search', 'perPage'],
    paginated: true,
    metrics: [
      { key: 'total_amount', label: 'إجمالي المبلغ', format: 'money', tone: 'danger' },
      { key: 'total_quantity', label: 'إجمالي الكمية', format: 'number', tone: 'warning' },
      { key: 'total_return_transactions', label: 'عدد العمليات', format: 'number', tone: 'info' },
    ],
    sections: [
      {
        id: 'rows',
        title: 'المنتجات',
        extractRows: (p) => reportRows(p, ['data', 'rows', 'products']),
        fields: productReturnFields,
        titleKey: 'product_name',
        metaKey: 'returned_amount',
      },
    ],
  },
  {
    id: 'purchase-returns-by-product',
    title: 'مرتجعات شراء بالمنتج',
    description: 'مرتجعات المشتريات مجمعة حسب المنتج',
    group: 'purchases',
    icon: 'shopping-cart',
    webRoute: '/reports/purchase-returns-by-product',
    permission: 'view_reports',
    apiMethod: 'purchaseReturnsByProduct',
    filters: ['dateRange', 'branch', 'category', 'product', 'search', 'perPage'],
    paginated: true,
    metrics: [
      { key: 'total_amount', label: 'إجمالي المبلغ', format: 'money', tone: 'danger' },
      { key: 'total_quantity', label: 'إجمالي الكمية', format: 'number', tone: 'warning' },
      { key: 'total_return_transactions', label: 'عدد العمليات', format: 'number', tone: 'info' },
    ],
    sections: [
      {
        id: 'rows',
        title: 'المنتجات',
        extractRows: (p) => reportRows(p, ['data', 'rows', 'products']),
        fields: productReturnFields,
        titleKey: 'product_name',
        metaKey: 'returned_amount',
      },
    ],
  },
  {
    id: 'sales-tax',
    title: 'تقرير الضرائب',
    description: 'إجمالي الضريبة والإيراد حسب المنتج',
    group: 'sales',
    icon: 'receipt-long',
    webRoute: '/reports/sales/tax',
    permission: 'view_reports',
    apiMethod: 'tax',
    filters: ['dateRange'],
    metrics: [
      { key: 'total_revenue', label: 'إجمالي الإيراد', format: 'money', tone: 'primary' },
      { key: 'total_tax', label: 'إجمالي الضريبة', format: 'money', tone: 'warning' },
      { key: 'effective_rate', label: 'معدل الضريبة', format: 'percent', tone: 'info' },
    ],
    sections: [
      {
        id: 'by-product',
        title: 'حسب المنتج',
        extractRows: (p) => reportRows(p, ['by_product']),
        fields: [
          { key: 'product_name', label: 'المنتج', format: 'text', primary: true },
          { key: 'revenue', label: 'الإيراد', format: 'money' },
          { key: 'tax', label: 'الضريبة', format: 'money' },
        ],
      },
    ],
  },
  {
    id: 'sales-layaway',
    title: 'البيع الآجل',
    description: 'خطط التقسيط والأقساط المتبقية',
    group: 'sales',
    icon: 'schedule',
    webRoute: '/reports/sales/layaway',
    permission: 'view_reports',
    apiMethod: 'layaway',
    filters: [],
    metrics: [
      { key: 'totalPlans', label: 'إجمالي الخطط', format: 'number', tone: 'info' },
      { key: 'activePlans', label: 'خطط نشطة', format: 'number', tone: 'primary' },
      { key: 'totalRemaining', label: 'المتبقي', format: 'money', tone: 'warning' },
      { key: 'totalAmount', label: 'إجمالي المبلغ', format: 'money', tone: 'success' },
    ],
    sections: [
      {
        id: 'plans',
        title: 'الخطط',
        extractRows: (p) => reportRows(p, ['plans', 'items']),
        fields: [
          { key: 'customer_name', label: 'العميل', format: 'text', primary: true },
          { key: 'total_amount', label: 'الإجمالي', format: 'money' },
          { key: 'paid_amount', label: 'المدفوع', format: 'money' },
          { key: 'remaining_amount', label: 'المتبقي', format: 'money' },
          { key: 'status', label: 'الحالة', format: 'badge' },
        ],
      },
    ],
  },
  {
    id: 'sales-hourly',
    title: 'مبيعات بالساعة',
    description: 'توزيع المبيعات على ساعات اليوم',
    group: 'sales',
    icon: 'access-time',
    webRoute: '/reports/sales/hourly',
    permission: 'view_reports',
    apiMethod: 'hourlySales',
    filters: ['dateRange'],
    chart: { sectionId: 'hourly', labelKey: 'hour', valueKey: 'revenue', valueFormat: 'money' },
    metrics: [
      { key: 'peak_hour', label: 'ساعة الذروة', format: 'text', tone: 'info' },
      { key: 'peak_revenue', label: 'إيراد الذروة', format: 'money', tone: 'primary' },
      { key: 'total_revenue', label: 'إجمالي الإيراد', format: 'money', tone: 'success' },
    ],
    sections: [
      {
        id: 'hourly',
        title: 'حسب الساعة',
        extractRows: (p) => reportRows(p, ['hourly', 'hours']),
        fields: [
          { key: 'hour', label: 'الساعة', format: 'text', primary: true },
          { key: 'revenue', label: 'الإيراد', format: 'money' },
          { key: 'orders_count', label: 'الطلبات', format: 'number' },
        ],
      },
    ],
  },
  {
    id: 'inventory-valuation',
    title: 'تقييم المخزون',
    description: 'قيمة المخزون حسب المستودع',
    group: 'inventory',
    icon: 'warehouse',
    webRoute: '/reports/inventory/valuation',
    permission: 'view_reports',
    apiMethod: 'inventoryValuation',
    useAggregates: true,
    filters: ['warehouse', 'category', 'perPage'],
    paginated: true,
    exportSupported: true,
    exportType: 'inventory',
    metrics: [
      { key: 'grand_total_value', label: 'إجمالي قيمة المخزون', format: 'money', tone: 'primary' },
      { key: 'total_quantity', label: 'إجمالي الكمية', format: 'number', tone: 'info' },
      { key: 'product_count', label: 'عدد المنتجات', format: 'number' },
      { key: 'warehouse_count', label: 'عدد المستودعات', format: 'number' },
    ],
    sections: [
      {
        id: 'by_warehouse',
        title: 'حسب المستودع',
        extractRows: (p) => reportRows(p, ['by_warehouse']),
        fields: [
          { key: 'warehouse_name', label: 'المستودع', format: 'text', primary: true },
          { key: 'total_quantity', label: 'الكمية', format: 'number' },
          { key: 'total_value', label: 'القيمة', format: 'money' },
        ],
      },
      {
        id: 'by_category',
        title: 'حسب الفئة',
        extractRows: (p) => reportRows(p, ['by_category']),
        fields: [
          { key: 'category_name', label: 'الفئة', format: 'text', primary: true },
          { key: 'product_count', label: 'عدد المنتجات', format: 'number' },
          { key: 'total_value', label: 'القيمة', format: 'money' },
        ],
      },
      {
        id: 'products',
        title: 'المنتجات',
        extractRows: (p) => reportRows(p, ['rows', 'products']),
        fields: [
          { key: 'product_name', label: 'المنتج', format: 'text', primary: true },
          { key: 'quantity', label: 'الكمية', format: 'number' },
          { key: 'unit_cost', label: 'تكلفة الوحدة', format: 'money' },
          { key: 'total_value', label: 'القيمة', format: 'money' },
        ],
      },
    ],
  },
  {
    id: 'inventory-movements',
    title: 'حركات المخزون',
    description: 'تحويلات وتسويات المخزون',
    group: 'inventory',
    icon: 'swap-horiz',
    webRoute: '/reports/inventory/movements',
    permission: 'view_reports',
    apiMethod: 'inventoryMovements',
    useAggregates: true,
    filters: ['dateRange', 'warehouse', 'movementType', 'perPage'],
    paginated: true,
    metrics: [
      { key: 'transfers_count', label: 'عدد التحويلات', format: 'number', tone: 'info' },
      { key: 'adjustments_count', label: 'عدد التسويات', format: 'number', tone: 'warning' },
      { key: 'total_items_moved', label: 'إجمالي الأصناف', format: 'number' },
      { key: 'net_transfers', label: 'صافي التحويلات', format: 'number' },
    ],
    sections: [
      {
        id: 'by_warehouse',
        title: 'حسب المستودع',
        extractRows: (p) => reportRows(p, ['by_warehouse']),
        fields: [
          { key: 'warehouse_name', label: 'المستودع', format: 'text', primary: true },
          { key: 'transfers_count', label: 'تحويلات', format: 'number' },
          { key: 'adjustments_count', label: 'تسويات', format: 'number' },
        ],
      },
      {
        id: 'rows',
        title: 'الحركات',
        extractRows: (p) => reportRows(p, ['rows']),
        fields: [
          { key: 'reference', label: 'المرجع', format: 'text', primary: true },
          { key: 'movement_type', label: 'النوع', format: 'badge' },
          { key: 'from_warehouse', label: 'من', format: 'text' },
          { key: 'to_warehouse', label: 'إلى', format: 'text' },
          { key: 'warehouse_name', label: 'المستودع', format: 'text' },
          { key: 'created_at', label: 'التاريخ', format: 'date' },
        ],
      },
    ],
  },
  {
    id: 'inventory-expiry',
    title: 'تقرير الصلاحية',
    description: 'دفعات قريبة الانتهاء أو منتهية',
    group: 'inventory',
    icon: 'event-busy',
    webRoute: '/reports/inventory/expiry',
    permission: 'view_reports',
    apiMethod: 'inventoryExpiry',
    useAggregates: true,
    filters: ['branch', 'warehouse', 'product', 'expiryOptions', 'perPage'],
    paginated: true,
    metrics: [
      { key: 'expired_qty', label: 'كمية منتهية', format: 'number', tone: 'danger' },
      { key: 'near_expiry_qty', label: 'قريبة الانتهاء', format: 'number', tone: 'warning' },
      { key: 'unbatched_qty', label: 'بدون دفعة', format: 'number', tone: 'info' },
      { key: 'batch_count', label: 'عدد الدفعات', format: 'number' },
    ],
    sections: [
      {
        id: 'by_status',
        title: 'حسب الحالة',
        extractRows: (p) => reportRows(p, ['by_status']),
        fields: [
          { key: 'status', label: 'الحالة', format: 'badge', primary: true },
          { key: 'quantity', label: 'الكمية', format: 'number' },
          { key: 'batch_count', label: 'الدفعات', format: 'number' },
        ],
      },
      {
        id: 'batches',
        title: 'الدفعات',
        extractRows: (p) => reportRows(p, ['rows']),
        fields: [
          { key: 'product_name', label: 'المنتج', format: 'text', primary: true },
          { key: 'batch_number', label: 'الدفعة', format: 'text' },
          { key: 'expiry_date', label: 'الانتهاء', format: 'date' },
          { key: 'quantity', label: 'الكمية', format: 'number' },
          { key: 'warehouse_name', label: 'المستودع', format: 'text' },
        ],
      },
    ],
  },
  {
    id: 'raw-materials',
    title: 'تقارير الخامات',
    description: 'مخزون، تنبيهات، صلاحية، ومشتريات الخامات',
    group: 'inventory',
    icon: 'science',
    webRoute: '/reports/inventory/raw-materials',
    permission: 'view_reports',
    apiMethod: 'rawMaterialsReport',
    filters: [],
    metrics: [],
    sections: [],
  },
  {
    id: 'customers-aging',
    title: 'أعمار ديون العملاء',
    description: 'توزيع الديون حسب فترات التأخير',
    group: 'customers',
    icon: 'people',
    webRoute: '/reports/customers/aging',
    permission: 'view_reports',
    apiMethod: 'customerAging',
    filters: [],
    metrics: [
      { key: 'total_debt', label: 'إجمالي الديون', format: 'money', tone: 'danger' },
      { key: 'total_customers', label: 'عدد العملاء', format: 'number', tone: 'info' },
      { key: 'days_90_plus', label: 'أكثر من 90 يوم', format: 'money', tone: 'warning' },
    ],
    sections: [
      {
        id: 'customers',
        title: 'العملاء',
        extractRows: (p) => reportRows(p, ['customers']),
        fields: [
          { key: 'name', label: 'العميل', format: 'text', primary: true },
          { key: 'debt', label: 'الدين', format: 'money' },
          { key: 'days_overdue', label: 'أيام التأخير', format: 'number' },
          { key: 'bucket', label: 'الفترة', format: 'badge' },
        ],
      },
    ],
  },
  {
    id: 'suppliers-aging',
    title: 'أعمار مستحقات الموردين',
    description: 'أرصدة الموردين وفترات الاستحقاق',
    group: 'suppliers',
    icon: 'local-shipping',
    webRoute: '/reports/suppliers/aging',
    permission: 'view_reports',
    apiMethod: 'supplierAging',
    filters: [],
    metrics: [
      { key: 'total_balance', label: 'إجمالي المستحق', format: 'money', tone: 'danger' },
      { key: 'total_suppliers', label: 'عدد الموردين', format: 'number', tone: 'info' },
    ],
    sections: [
      {
        id: 'suppliers',
        title: 'الموردون',
        extractRows: (p) => reportRows(p, ['suppliers']),
        fields: [
          { key: 'name', label: 'المورد', format: 'text', primary: true },
          { key: 'balance', label: 'الرصيد', format: 'money' },
          { key: 'days', label: 'الأيام', format: 'number' },
          { key: 'bucket', label: 'الفترة', format: 'badge' },
        ],
      },
    ],
  },
  {
    id: 'marketing-coupons',
    title: 'تقرير الكوبونات',
    description: 'استخدامات الكوبونات والخصومات',
    group: 'marketing',
    icon: 'local-offer',
    webRoute: '/reports/marketing/coupons',
    permission: 'view_reports',
    apiMethod: 'coupons',
    filters: ['dateRange', 'couponCode', 'perPage'],
    paginated: true,
    exportSupported: true,
    exportType: 'coupons',
    metrics: [
      { key: 'total_usages', label: 'عدد الاستخدامات', format: 'number', tone: 'info' },
      { key: 'total_coupon_discount', label: 'إجمالي الخصم', format: 'money', tone: 'warning' },
      { key: 'net_sales_after_coupon', label: 'صافي المبيعات', format: 'money', tone: 'success' },
    ],
    sections: [
      {
        id: 'usages',
        title: 'الاستخدامات',
        extractRows: (p) => reportRows(p, ['usages']),
        fields: [
          { key: 'coupon_code', label: 'الكوبون', format: 'text', primary: true },
          { key: 'discount_amount', label: 'الخصم', format: 'money' },
          { key: 'sale_total', label: 'قيمة الفاتورة', format: 'money' },
          { key: 'used_at', label: 'التاريخ', format: 'date' },
        ],
      },
      {
        id: 'by-coupon',
        title: 'حسب الكوبون',
        extractRows: (p) => reportRows(p, ['by_coupon']),
        fields: [
          { key: 'coupon_code', label: 'الكوبون', format: 'text', primary: true },
          { key: 'usage_count', label: 'الاستخدامات', format: 'number' },
          { key: 'total_discount', label: 'الخصم', format: 'money' },
        ],
      },
    ],
  },
  {
    id: 'marketing-promotions',
    title: 'تقرير العروض',
    description: 'العروض الترويجية النشطة والمنتهية',
    group: 'marketing',
    icon: 'campaign',
    webRoute: '/reports/marketing/promotions',
    permission: 'view_reports',
    apiMethod: 'promotions',
    filters: [],
    metrics: [
      { key: 'total_promotions', label: 'إجمالي العروض', format: 'number', tone: 'info' },
      { key: 'active', label: 'عروض نشطة', format: 'number', tone: 'success' },
    ],
    sections: [
      {
        id: 'promotions',
        title: 'العروض',
        extractRows: (p) => reportRows(p, ['promotions']),
        fields: [
          { key: 'name', label: 'العرض', format: 'text', primary: true },
          { key: 'type', label: 'النوع', format: 'text' },
          { key: 'is_active', label: 'نشط', format: 'badge' },
          { key: 'start_date', label: 'البداية', format: 'date' },
          { key: 'end_date', label: 'النهاية', format: 'date' },
        ],
      },
    ],
  },
  {
    id: 'gift-cards',
    title: 'بطاقات الهدايا',
    description: 'أرصدة واستخدام بطاقات الهدايا',
    group: 'marketing',
    icon: 'card-giftcard',
    webRoute: '/reports/gift-cards',
    permission: 'view_reports',
    apiMethod: 'giftCards',
    filters: [],
    metrics: [
      { key: 'total_cards', label: 'عدد البطاقات', format: 'number', tone: 'info' },
      { key: 'total_remaining', label: 'الرصيد المتبقي', format: 'money', tone: 'success' },
      { key: 'total_used', label: 'المستخدم', format: 'money', tone: 'warning' },
    ],
    sections: [
      {
        id: 'cards',
        title: 'البطاقات',
        extractRows: (p) => reportRows(p, ['cards']),
        fields: [
          { key: 'code', label: 'الكود', format: 'text', primary: true },
          { key: 'remaining_balance', label: 'المتبقي', format: 'money' },
          { key: 'initial_balance', label: 'الرصيد الابتدائي', format: 'money' },
          { key: 'expires_at', label: 'الانتهاء', format: 'date' },
        ],
      },
    ],
  },
  {
    id: 'treasury',
    title: 'تقرير الخزينة',
    description: 'تدفقات النقد داخل وخارج الخزائن',
    group: 'finance',
    icon: 'account-balance-wallet',
    webRoute: '/reports/treasury',
    permission: 'view_reports',
    feature: 'advanced_reports',
    apiMethod: 'treasurySummary',
    filters: ['dateRange', 'branch'],
    chart: { sectionId: 'vaults', labelKey: 'name', valueKey: 'balance', valueFormat: 'money' },
    metrics: [
      { key: 'total_cash_in', label: 'إجمالي الوارد', format: 'money', tone: 'success' },
      { key: 'total_cash_out', label: 'إجمالي الصادر', format: 'money', tone: 'danger' },
      { key: 'net_balance', label: 'صافي الرصيد', format: 'money', tone: 'primary' },
    ],
    sections: [
      {
        id: 'vaults',
        title: 'الخزائن',
        extractRows: (p) => reportRows(p, ['vaults']),
        fields: [
          { key: 'name', label: 'الخزينة', format: 'text', primary: true },
          { key: 'cash_in', label: 'وارد', format: 'money' },
          { key: 'cash_out', label: 'صادر', format: 'money' },
          { key: 'balance', label: 'الرصيد', format: 'money' },
        ],
      },
    ],
  },
  {
    id: 'expenses',
    title: 'تقرير المصروفات',
    description: 'المصروفات حسب التصنيف واليوم',
    group: 'finance',
    icon: 'payments',
    webRoute: '/reports/expenses',
    permission: 'view_reports',
    feature: 'advanced_reports',
    apiMethod: 'expensesSummary',
    filters: ['dateRange', 'branch'],
    chart: { sectionId: 'by-category', labelKey: 'category_name', valueKey: 'total', valueFormat: 'money' },
    metrics: [
      { key: 'total_expenses', label: 'إجمالي المصروفات', format: 'money', tone: 'danger' },
    ],
    sections: [
      {
        id: 'by-category',
        title: 'حسب التصنيف',
        extractRows: (p) => reportRows(p, ['by_category']),
        fields: [
          { key: 'category_name', label: 'التصنيف', format: 'text', primary: true },
          { key: 'total', label: 'المبلغ', format: 'money' },
          { key: 'count', label: 'العدد', format: 'number' },
        ],
      },
    ],
  },
  {
    id: 'profit-loss-operational',
    title: 'الأرباح والخسائر',
    description: 'قائمة دخل تشغيلية بدون موازنة: إيرادات، تكلفة، عمالة، ومصروفات.',
    group: 'finance',
    icon: 'trending-up',
    webRoute: '/reports/profit-loss',
    permission: 'view_reports',
    feature: 'advanced_reports',
    apiMethod: 'profitLossOperational',
    filters: ['dateRange', 'branch'],
    metrics: [
      { key: 'net_sales', label: 'صافي المبيعات', format: 'money', tone: 'primary' },
      { key: 'gross_profit', label: 'مجمل الربح', format: 'money', tone: 'success' },
      { key: 'gross_margin_pct', label: 'هامش مجمل %', format: 'number', tone: 'info' },
      { key: 'prime_cost_pct', label: 'التكلفة الأساسية %', format: 'number', tone: 'warning' },
      { key: 'net_profit', label: 'صافي الربح', format: 'money', tone: 'success' },
      { key: 'net_margin_pct', label: 'هامش صافي %', format: 'number', tone: 'info' },
    ],
    sections: [
      {
        id: 'lines',
        title: 'قائمة الدخل',
        extractRows: (p) => {
          const data = (p as any)?.data ?? p
          const sections = Array.isArray(data?.sections) ? data.sections : []
          const rows: Record<string, unknown>[] = []
          for (const section of sections) {
            const sectionLabel = String(section?.label || section?.section || '')
            for (const row of section?.rows || []) {
              if (row?.is_memo) continue
              rows.push({
                section: sectionLabel,
                label: row?.label,
                amount: row?.amount,
                pct_of_revenue: row?.pct_of_revenue,
                is_total: row?.is_total,
              })
            }
          }
          return rows
        },
        fields: [
          { key: 'section', label: 'القسم', format: 'text' },
          { key: 'label', label: 'البند', format: 'text', primary: true },
          { key: 'amount', label: 'المبلغ', format: 'money' },
          { key: 'pct_of_revenue', label: '% من الإيراد', format: 'number' },
        ],
      },
    ],
  },
  {
    id: 'budget-vs-actual',
    title: 'الموازنة مقابل الفعلي',
    description: 'مقارنة المخطط بالمحقق للإيرادات والتكاليف والمصروفات. أدِر الموازنات من الويب.',
    group: 'finance',
    icon: 'pie-chart',
    webRoute: '/reports/budget-vs-actual',
    permission: 'view_reports',
    feature: 'advanced_reports',
    apiMethod: 'budgetVsActual',
    filters: ['dateRange', 'branch'],
    metrics: [
      { key: 'budget_revenue', label: 'هدف الإيراد', format: 'money', tone: 'info' },
      { key: 'actual_revenue', label: 'الإيراد الفعلي', format: 'money', tone: 'success' },
      { key: 'actual_net_profit', label: 'صافي الربح', format: 'money', tone: 'primary' },
      { key: 'actual_prime_cost_pct', label: 'التكلفة الأساسية %', format: 'number', tone: 'warning' },
      { key: 'unbudgeted_expenses', label: 'خارج الموازنة', format: 'money', tone: 'danger' },
    ],
    sections: [
      {
        id: 'lines',
        title: 'بنود الموازنة',
        extractRows: (p) => {
          const data = (p as any)?.data ?? p
          if (data?.status === 'missing_budget') return []
          const sections = Array.isArray(data?.sections) ? data.sections : []
          const rows: Record<string, unknown>[] = []
          for (const section of sections) {
            const sectionLabel = String(section?.label || section?.section || '')
            for (const row of section?.rows || []) {
              rows.push({
                section: sectionLabel,
                label: row?.label,
                budget: row?.budget,
                actual: row?.actual,
                variance: row?.variance,
                variance_pct: row?.variance_pct,
                favorable: row?.favorable,
              })
            }
          }
          return rows
        },
        fields: [
          { key: 'section', label: 'القسم', format: 'text' },
          { key: 'label', label: 'البند', format: 'text', primary: true },
          { key: 'budget', label: 'المخطط', format: 'money' },
          { key: 'actual', label: 'الفعلي', format: 'money' },
          { key: 'variance', label: 'الفرق', format: 'money' },
          { key: 'variance_pct', label: 'الفرق %', format: 'number' },
        ],
      },
    ],
  },
  {
    id: 'dining',
    title: 'تقرير المطاعم',
    description: 'إشغال الطاولات وأداء النادل',
    group: 'operations',
    icon: 'restaurant',
    webRoute: '/reports/dining',
    permission: 'view_reports',
    apiMethod: 'dining',
    filters: ['dateRange'],
    metrics: [
      { key: 'total_tables', label: 'الطاولات', format: 'number', tone: 'info' },
      { key: 'occupied', label: 'مشغولة', format: 'number', tone: 'warning' },
      { key: 'utilization', label: 'نسبة الإشغال', format: 'percent', tone: 'primary' },
    ],
    sections: [
      {
        id: 'waiters',
        title: 'أداء النادل',
        extractRows: (p) => reportRows(p, ['waiter_performance']),
        fields: [
          { key: 'waiter_name', label: 'النادل', format: 'text', primary: true },
          { key: 'orders', label: 'الطلبات', format: 'number' },
          { key: 'revenue', label: 'الإيراد', format: 'money' },
        ],
      },
    ],
  },
  {
    id: 'delivery',
    title: 'تقرير التوصيل',
    description: 'التوصيلات والرسوم حسب السائق',
    group: 'operations',
    icon: 'delivery-dining',
    webRoute: '/reports/delivery',
    permission: 'view_reports',
    apiMethod: 'delivery',
    filters: ['dateRange'],
    metrics: [
      { key: 'total_deliveries', label: 'عدد التوصيلات', format: 'number', tone: 'info' },
      { key: 'total_fees', label: 'إجمالي الرسوم', format: 'money', tone: 'primary' },
      { key: 'avg_fee', label: 'متوسط الرسوم', format: 'money', tone: 'warning' },
    ],
    sections: [
      {
        id: 'deliveries',
        title: 'التوصيلات',
        extractRows: (p) => reportRows(p, ['deliveries']),
        fields: [
          { key: 'order_number', label: 'الطلب', format: 'text', primary: true },
          { key: 'driver_name', label: 'السائق', format: 'text' },
          { key: 'fee', label: 'الرسوم', format: 'money' },
          { key: 'status', label: 'الحالة', format: 'badge' },
        ],
      },
      {
        id: 'by-driver',
        title: 'حسب السائق',
        extractRows: (p) => reportRows(p, ['by_driver']),
        fields: [
          { key: 'driver_name', label: 'السائق', format: 'text', primary: true },
          { key: 'count', label: 'العدد', format: 'number' },
          { key: 'total_fees', label: 'الرسوم', format: 'money' },
        ],
      },
    ],
  },
  {
    id: 'shifts',
    title: 'أداء الورديات',
    description: 'مبيعات الورديات والفروقات النقدية',
    group: 'operations',
    icon: 'schedule',
    webRoute: '/reports/shifts',
    permission: 'view_reports',
    feature: 'advanced_reports',
    apiMethod: 'shiftPerformance',
    filters: ['dateRange', 'branch'],
    metrics: [
      { key: 'total_shifts', label: 'عدد الورديات', format: 'number', tone: 'info' },
      { key: 'total_sales_total', label: 'إجمالي المبيعات', format: 'money', tone: 'primary' },
      { key: 'avg_discrepancy', label: 'متوسط الفرق', format: 'money', tone: 'warning' },
    ],
    sections: [
      {
        id: 'shifts',
        title: 'الورديات',
        extractRows: (p) => reportRows(p, ['shifts']),
        fields: [
          { key: 'cashier_name', label: 'الكاشير', format: 'text', primary: true },
          { key: 'sales_total', label: 'المبيعات', format: 'money' },
          { key: 'sales_count', label: 'عدد الفواتير', format: 'number' },
          { key: 'discrepancy', label: 'الفرق', format: 'money' },
          { key: 'closed_at', label: 'الإغلاق', format: 'date' },
        ],
      },
    ],
  },
  {
    id: 'saved-reports',
    title: 'التقارير المحفوظة',
    description: 'تقارير محفوظة مسبقاً من الويب',
    group: 'other',
    icon: 'bookmark',
    webRoute: '/reports/saved',
    permission: 'view_reports',
    apiMethod: 'savedList',
    filters: ['perPage'],
    paginated: true,
    metrics: [],
    sections: [
      {
        id: 'saved',
        title: 'المحفوظة',
        extractRows: (p) => {
          const data = reportSummary(p);
          const nested = data.data;
          if (Array.isArray(nested)) return nested as Record<string, unknown>[];
          return reportRows(p, ['data']);
        },
        fields: [
          { key: 'name', label: 'الاسم', format: 'text', primary: true },
          { key: 'type', label: 'النوع', format: 'text' },
          { key: 'branch_name', label: 'الفرع', format: 'text' },
          { key: 'created_at', label: 'تاريخ الحفظ', format: 'date' },
        ],
      },
    ],
  },
  {
    id: 'partner-performance',
    title: 'تقارير الشريك',
    description: 'ملخص المبيعات والأرباح حسب الفترة (صلاحية شريك)',
    group: 'other',
    icon: 'business-center',
    webRoute: '/reports/partner',
    permission: 'view_partner_reports',
    usePartnerApi: true,
    apiMethod: 'comprehensive',
    filters: ['dateRange', 'branch'],
    metrics: [
      { key: 'total_sales', label: 'إجمالي المبيعات', format: 'money', tone: 'primary' },
      { key: 'sales_count', label: 'عدد الفواتير', format: 'number', tone: 'info' },
      { key: 'net_profit', label: 'صافي الربح', format: 'money', tone: 'success' },
      { key: 'profit_margin', label: 'هامش الربح', format: 'percent', tone: 'warning' },
    ],
    sections: [
      {
        id: 'branches',
        title: 'حسب الفرع',
        extractRows: (p) => reportRows(p, ['by_branch']),
        fields: [
          { key: 'branch_name', label: 'الفرع', format: 'text', primary: true },
          { key: 'total_sales', label: 'المبيعات', format: 'money' },
          { key: 'sales_count', label: 'العدد', format: 'number' },
          { key: 'net', label: 'الصافي', format: 'money' },
        ],
      },
      {
        id: 'top-products',
        title: 'أفضل المنتجات',
        extractRows: (p) => reportRows(p, ['top_products']),
        fields: [
          { key: 'name', label: 'المنتج', format: 'text', primary: true },
          { key: 'total_revenue', label: 'الإيراد', format: 'money' },
          { key: 'total_quantity', label: 'الكمية', format: 'number' },
        ],
      },
    ],
  },
  {
    id: 'inventory-stock-counts',
    title: 'تقرير الجرد',
    description: 'جلسات الجرد وحالاتها',
    group: 'inventory',
    icon: 'fact-check',
    webRoute: '/reports/inventory/stock-counts',
    permission: 'view_reports',
    apiMethod: 'stockCounts',
    filters: ['dateRange', 'branch', 'status', 'perPage'],
    paginated: true,
    metrics: [
      { key: 'total_counts', label: 'إجمالي الجرد', format: 'number', tone: 'info' },
      { key: 'posted', label: 'مرحّل', format: 'number', tone: 'success' },
      { key: 'draft', label: 'مسودة', format: 'number', tone: 'warning' },
      { key: 'cancelled', label: 'ملغي', format: 'number', tone: 'danger' },
    ],
    sections: [
      {
        id: 'counts',
        title: 'جلسات الجرد',
        extractRows: (p) => reportRows(p, ['counts']),
        fields: [
          { key: 'warehouse_name', label: 'المستودع', format: 'text', primary: true },
          { key: 'status', label: 'الحالة', format: 'badge' },
          { key: 'created_by_name', label: 'أنشأها', format: 'text' },
          { key: 'notes', label: 'ملاحظات', format: 'text' },
          { key: 'created_at', label: 'التاريخ', format: 'date' },
          { key: 'posted_at', label: 'ترحيل', format: 'date' },
        ],
      },
    ],
  },
  {
    id: 'inventory-stock-adjustments',
    title: 'تقرير التسويات',
    description: 'تسويات المخزون والقيم',
    group: 'inventory',
    icon: 'tune',
    webRoute: '/reports/inventory/stock-adjustments',
    permission: 'view_reports',
    apiMethod: 'stockAdjustments',
    filters: ['dateRange', 'branch', 'type', 'perPage'],
    paginated: true,
    metrics: [
      { key: 'total_adjustments', label: 'عدد التسويات', format: 'number', tone: 'info' },
      { key: 'total_value', label: 'إجمالي القيمة', format: 'money', tone: 'warning' },
    ],
    sections: [
      {
        id: 'adjustments',
        title: 'التسويات',
        extractRows: (p) => reportRows(p, ['adjustments']),
        fields: [
          { key: 'reference_no', label: 'المرجع', format: 'text', primary: true },
          { key: 'type', label: 'النوع', format: 'badge' },
          { key: 'warehouse_name', label: 'المستودع', format: 'text' },
          { key: 'reason', label: 'السبب', format: 'text' },
          { key: 'status', label: 'الحالة', format: 'badge' },
          { key: 'created_by_name', label: 'أنشأها', format: 'text' },
          { key: 'created_at', label: 'التاريخ', format: 'date' },
        ],
      },
    ],
  },
  {
    id: 'inventory-stock-transfers',
    title: 'تقرير التحويلات',
    description: 'تحويلات بين المستودعات وتكاليف الشحن',
    group: 'inventory',
    icon: 'swap-horiz',
    webRoute: '/reports/inventory/stock-transfers',
    permission: 'view_reports',
    apiMethod: 'stockTransfers',
    filters: ['dateRange', 'warehouse', 'status', 'perPage'],
    paginated: true,
    metrics: [
      { key: 'total_transfers', label: 'إجمالي التحويلات', format: 'number', tone: 'info' },
      { key: 'completed', label: 'مكتمل', format: 'number', tone: 'success' },
      { key: 'in_transit', label: 'في الطريق', format: 'number', tone: 'warning' },
      { key: 'total_shipping_cost', label: 'تكلفة الشحن', format: 'money', tone: 'primary' },
    ],
    sections: [
      {
        id: 'transfers',
        title: 'التحويلات',
        extractRows: (p) => reportRows(p, ['transfers']),
        fields: [
          { key: 'reference_no', label: 'المرجع', format: 'text', primary: true },
          { key: 'from_warehouse', label: 'من', format: 'text' },
          { key: 'to_warehouse', label: 'إلى', format: 'text' },
          { key: 'status', label: 'الحالة', format: 'badge' },
          { key: 'shipping_cost', label: 'الشحن', format: 'money' },
          { key: 'created_by_name', label: 'أنشأها', format: 'text' },
          { key: 'created_at', label: 'التاريخ', format: 'date' },
        ],
      },
    ],
  },
  {
    id: 'inventory-warehouse-utilization',
    title: 'استخدام المستودعات',
    description: 'قيمة المخزون وعدد SKUs لكل مستودع',
    group: 'inventory',
    icon: 'warehouse',
    webRoute: '/reports/inventory/warehouse-utilization',
    permission: 'view_reports',
    apiMethod: 'warehouseUtilization',
    filters: ['warehouse', 'perPage'],
    paginated: true,
    metrics: [
      { key: 'total_warehouses', label: 'المستودعات', format: 'number', tone: 'info' },
      { key: 'total_skus', label: 'إجمالي SKUs', format: 'number', tone: 'warning' },
      { key: 'total_inventory_value', label: 'قيمة المخزون', format: 'money', tone: 'primary' },
    ],
    sections: [
      {
        id: 'warehouses',
        title: 'المستودعات',
        extractRows: (p) => reportRows(p, ['warehouses']),
        fields: [
          { key: 'name', label: 'المستودع', format: 'text', primary: true },
          { key: 'code', label: 'الكود', format: 'text' },
          { key: 'sku_count', label: 'SKUs', format: 'number' },
          { key: 'total_quantity', label: 'الكمية', format: 'number' },
          { key: 'inventory_value', label: 'القيمة', format: 'money' },
          { key: 'branch_names', label: 'الفروع', format: 'text' },
        ],
      },
    ],
  },
  {
    id: 'products-variants',
    title: 'متغيرات المنتجات',
    description: 'متغيرات المنتجات وأسعارها الإضافية',
    group: 'inventory',
    icon: 'category',
    webRoute: '/reports/products/variants',
    permission: 'view_reports',
    apiMethod: 'productVariants',
    filters: ['branch', 'product', 'perPage'],
    paginated: true,
    metrics: [
      { key: 'total_variants', label: 'إجمالي المتغيرات', format: 'number', tone: 'info' },
      { key: 'products_with_variants', label: 'منتجات بمتغيرات', format: 'number', tone: 'primary' },
      { key: 'total_additional_price', label: 'السعر الإضافي', format: 'money', tone: 'warning' },
    ],
    sections: [
      {
        id: 'variants',
        title: 'المتغيرات',
        extractRows: (p) => reportRows(p, ['variants']),
        fields: [
          { key: 'product_name', label: 'المنتج', format: 'text', primary: true },
          { key: 'sku', label: 'SKU', format: 'text' },
          { key: 'attributes', label: 'السمات', format: 'text' },
          { key: 'additional_price', label: 'سعر إضافي', format: 'money' },
          { key: 'created_at', label: 'التاريخ', format: 'date' },
        ],
      },
    ],
  },
  {
    id: 'customers-loyalty',
    title: 'نقاط الولاء',
    description: 'معاملات نقاط الولاء وأعلى العملاء',
    group: 'customers',
    icon: 'stars',
    webRoute: '/reports/customers/loyalty',
    permission: 'view_reports',
    apiMethod: 'loyalty',
    filters: ['dateRange', 'branch', 'customer', 'perPage'],
    paginated: true,
    metrics: [
      { key: 'total_transactions', label: 'المعاملات', format: 'number', tone: 'info' },
      { key: 'total_earned', label: 'نقاط مكتسبة', format: 'number', tone: 'success' },
      { key: 'total_redeemed', label: 'نقاط مستبدلة', format: 'number', tone: 'warning' },
      { key: 'unique_customers', label: 'عملاء', format: 'number', tone: 'primary' },
    ],
    sections: [
      {
        id: 'top-customers',
        title: 'أعلى العملاء',
        extractRows: (p) => reportRows(p, ['top_customers']),
        fields: [
          { key: 'customer_name', label: 'العميل', format: 'text', primary: true },
          { key: 'earned', label: 'مكتسب', format: 'number' },
          { key: 'redeemed', label: 'مستبدل', format: 'number' },
          { key: 'current_balance', label: 'الرصيد', format: 'number' },
        ],
      },
      {
        id: 'transactions',
        title: 'المعاملات',
        extractRows: (p) => reportRows(p, ['transactions']),
        fields: [
          { key: 'customer_name', label: 'العميل', format: 'text', primary: true },
          { key: 'points_earned', label: 'مكتسب', format: 'number' },
          { key: 'points_redeemed', label: 'مستبدل', format: 'number' },
          { key: 'description', label: 'الوصف', format: 'text' },
          { key: 'reference_type', label: 'النوع', format: 'text' },
          { key: 'created_at', label: 'التاريخ', format: 'date' },
        ],
      },
    ],
  },
  {
    id: 'customers-wallet',
    title: 'تقرير المحفظة',
    description: 'معاملات محفظة العملاء والأرصدة',
    group: 'customers',
    icon: 'account-balance-wallet',
    webRoute: '/reports/customers/wallet',
    permission: 'view_reports',
    apiMethod: 'wallet',
    filters: ['dateRange', 'branch', 'customer', 'type', 'perPage'],
    paginated: true,
    metrics: [
      { key: 'total_transactions', label: 'المعاملات', format: 'number', tone: 'info' },
      { key: 'total_credit', label: 'دائن', format: 'money', tone: 'success' },
      { key: 'total_debit', label: 'مدين', format: 'money', tone: 'danger' },
      { key: 'unique_customers', label: 'عملاء', format: 'number', tone: 'primary' },
    ],
    sections: [
      {
        id: 'transactions',
        title: 'المعاملات',
        extractRows: (p) => reportRows(p, ['transactions']),
        fields: [
          { key: 'customer_name', label: 'العميل', format: 'text', primary: true },
          { key: 'type', label: 'النوع', format: 'badge' },
          { key: 'amount', label: 'المبلغ', format: 'money' },
          { key: 'balance_after', label: 'الرصيد بعد', format: 'money' },
          { key: 'description', label: 'الوصف', format: 'text' },
          { key: 'user_name', label: 'بواسطة', format: 'text' },
          { key: 'created_at', label: 'التاريخ', format: 'date' },
        ],
      },
    ],
  },
  {
    id: 'suppliers-payments',
    title: 'مدفوعات الموردين',
    description: 'مدفوعات الموردين التفصيلية',
    group: 'suppliers',
    icon: 'payments',
    webRoute: '/reports/suppliers/payments',
    permission: 'view_reports',
    apiMethod: 'supplierPaymentsDetail',
    filters: ['dateRange', 'branch', 'supplier', 'perPage'],
    paginated: true,
    metrics: [
      { key: 'total_payments', label: 'عدد المدفوعات', format: 'number', tone: 'info' },
      { key: 'total_amount', label: 'إجمالي المبلغ', format: 'money', tone: 'primary' },
      { key: 'cash_total', label: 'نقدي', format: 'money', tone: 'success' },
      { key: 'bank_total', label: 'بنك', format: 'money', tone: 'warning' },
    ],
    sections: [
      {
        id: 'by-supplier',
        title: 'حسب المورد',
        extractRows: (p) => reportRows(p, ['by_supplier']),
        fields: [
          { key: 'supplier_name', label: 'المورد', format: 'text', primary: true },
          { key: 'payment_count', label: 'عدد المدفوعات', format: 'number' },
          { key: 'total_paid', label: 'المدفوع', format: 'money' },
        ],
      },
      {
        id: 'payments',
        title: 'المدفوعات',
        extractRows: (p) => reportRows(p, ['payments']),
        fields: [
          { key: 'supplier_name', label: 'المورد', format: 'text', primary: true },
          { key: 'amount', label: 'المبلغ', format: 'money' },
          { key: 'payment_method', label: 'الطريقة', format: 'badge' },
          { key: 'payment_date', label: 'التاريخ', format: 'date' },
          { key: 'reference_no', label: 'المرجع', format: 'text' },
          { key: 'purchase_invoice', label: 'فاتورة الشراء', format: 'text' },
          { key: 'notes', label: 'ملاحظات', format: 'text' },
        ],
      },
    ],
  },
  {
    id: 'suppliers-requisitions',
    title: 'طلبات الشراء',
    description: 'طلبات الشراء وحالاتها',
    group: 'suppliers',
    icon: 'assignment',
    webRoute: '/reports/suppliers/requisitions',
    permission: 'view_reports',
    apiMethod: 'purchaseRequisitions',
    filters: ['dateRange', 'branch', 'status', 'perPage'],
    paginated: true,
    metrics: [
      { key: 'total_requisitions', label: 'إجمالي الطلبات', format: 'number', tone: 'info' },
      { key: 'approved', label: 'معتمد', format: 'number', tone: 'success' },
      { key: 'submitted', label: 'مقدم', format: 'number', tone: 'warning' },
      { key: 'fulfilled', label: 'منجز', format: 'number', tone: 'primary' },
      { key: 'rejected', label: 'مرفوض', format: 'number', tone: 'danger' },
    ],
    sections: [
      {
        id: 'requisitions',
        title: 'الطلبات',
        extractRows: (p) => reportRows(p, ['requisitions']),
        fields: [
          { key: 'reference_no', label: 'المرجع', format: 'text', primary: true },
          { key: 'status', label: 'الحالة', format: 'badge' },
          { key: 'created_by_name', label: 'أنشأها', format: 'text' },
          { key: 'notes', label: 'ملاحظات', format: 'text' },
          { key: 'created_at', label: 'التاريخ', format: 'date' },
        ],
      },
    ],
  },
  {
    id: 'dining-reservations',
    title: 'حجوزات الطاولات',
    description: 'حجوزات الطاولات وحالاتها',
    group: 'operations',
    icon: 'event-seat',
    webRoute: '/reports/dining/reservations',
    permission: 'view_reports',
    apiMethod: 'tableReservations',
    filters: ['dateRange', 'branch', 'status', 'perPage'],
    paginated: true,
    metrics: [
      { key: 'total_reservations', label: 'إجمالي الحجوزات', format: 'number', tone: 'info' },
      { key: 'confirmed', label: 'مؤكدة', format: 'number', tone: 'success' },
      { key: 'pending', label: 'قيد الانتظار', format: 'number', tone: 'warning' },
      { key: 'completed', label: 'منجزة', format: 'number', tone: 'primary' },
      { key: 'cancelled', label: 'ملغاة', format: 'number', tone: 'danger' },
    ],
    sections: [
      {
        id: 'reservations',
        title: 'الحجوزات',
        extractRows: (p) => reportRows(p, ['reservations']),
        fields: [
          { key: 'customer_name', label: 'العميل', format: 'text', primary: true },
          { key: 'table_name', label: 'الطاولة', format: 'text' },
          { key: 'status', label: 'الحالة', format: 'badge' },
          { key: 'reserved_from', label: 'من', format: 'date' },
          { key: 'reserved_to', label: 'إلى', format: 'date' },
          { key: 'notes', label: 'ملاحظات', format: 'text' },
          { key: 'created_by_name', label: 'أنشأها', format: 'text' },
        ],
      },
    ],
  },
  {
    id: 'operations-driver-settlements',
    title: 'تسويات السائقين',
    description: 'تسويات السائقين والتسليمات',
    group: 'operations',
    icon: 'local-shipping',
    webRoute: '/reports/operations/driver-settlements',
    permission: 'view_reports',
    apiMethod: 'driverSettlements',
    filters: ['dateRange', 'branch', 'perPage'],
    paginated: true,
    metrics: [
      { key: 'total_settlements', label: 'التسويات', format: 'number', tone: 'info' },
      { key: 'total_deliveries', label: 'التسليمات', format: 'number', tone: 'primary' },
      { key: 'total_collected', label: 'المحصّل', format: 'money', tone: 'success' },
      { key: 'total_earnings', label: 'أرباح السائقين', format: 'money', tone: 'warning' },
      { key: 'total_due', label: 'المستحق', format: 'money', tone: 'danger' },
      { key: 'total_received', label: 'المستلم', format: 'money', tone: 'primary' },
    ],
    sections: [
      {
        id: 'by-driver',
        title: 'حسب السائق',
        extractRows: (p) => reportRows(p, ['by_driver']),
        fields: [
          { key: 'driver_name', label: 'السائق', format: 'text', primary: true },
          { key: 'settlement_count', label: 'عدد التسويات', format: 'number' },
          { key: 'deliveries', label: 'التسليمات', format: 'number' },
          { key: 'earnings', label: 'الأرباح', format: 'money' },
        ],
      },
      {
        id: 'settlements',
        title: 'التسويات',
        extractRows: (p) => reportRows(p, ['settlements']),
        fields: [
          { key: 'driver_name', label: 'السائق', format: 'text', primary: true },
          { key: 'period_from', label: 'من', format: 'date' },
          { key: 'period_to', label: 'إلى', format: 'date' },
          { key: 'deliveries_count', label: 'التسليمات', format: 'number' },
          { key: 'total_collected', label: 'المحصّل', format: 'money' },
          { key: 'total_driver_earnings', label: 'الأرباح', format: 'money' },
          { key: 'total_due_from_driver', label: 'المستحق من السائق', format: 'money' },
          { key: 'amount_received', label: 'المستلم', format: 'money' },
          { key: 'difference', label: 'الفرق', format: 'money' },
          { key: 'status', label: 'الحالة', format: 'badge' },
          { key: 'settled_at', label: 'تاريخ التسوية', format: 'date' },
        ],
      },
    ],
  },
  {
    id: 'operations-cash-drawer',
    title: 'تقرير الدرج',
    description: 'حركات الدرج النقدية',
    group: 'operations',
    icon: 'point-of-sale',
    webRoute: '/reports/operations/cash-drawer',
    permission: 'view_reports',
    apiMethod: 'cashDrawer',
    filters: ['dateRange', 'branch', 'perPage'],
    paginated: true,
    metrics: [
      { key: 'total_drawer_txns', label: 'معاملات الدرج', format: 'number', tone: 'info' },
      { key: 'total_in', label: 'إيداع', format: 'money', tone: 'success' },
      { key: 'total_out', label: 'سحب', format: 'money', tone: 'danger' },
      { key: 'total_cash_movements', label: 'حركات نقدية', format: 'number', tone: 'primary' },
      { key: 'total_added', label: 'مضاف نقدي', format: 'money', tone: 'success' },
      { key: 'total_removed', label: 'مسحوب نقدي', format: 'money', tone: 'danger' },
    ],
    sections: [
      {
        id: 'transactions',
        title: 'الحركات',
        extractRows: (p) => reportRows(p, ['transactions']),
        fields: [
          { key: 'user_name', label: 'المستخدم', format: 'text', primary: true },
          { key: 'type', label: 'النوع', format: 'badge' },
          { key: 'direction', label: 'الاتجاه', format: 'badge' },
          { key: 'amount', label: 'المبلغ', format: 'money' },
          { key: 'source', label: 'المصدر', format: 'text' },
          { key: 'notes', label: 'ملاحظات', format: 'text' },
          { key: 'created_at', label: 'التاريخ', format: 'date' },
        ],
      },
    ],
  },
  {
    id: 'operations-kitchen-performance',
    title: 'أداء المطبخ',
    description: 'متوسط أوقات التحضير وأداء المحطات',
    group: 'operations',
    icon: 'restaurant',
    webRoute: '/reports/operations/kitchen-performance',
    permission: 'view_reports',
    apiMethod: 'kitchenPerformance',
    filters: ['dateRange', 'branch', 'perPage'],
    paginated: true,
    metrics: [
      { key: 'total_orders', label: 'الطلبات', format: 'number', tone: 'info' },
      { key: 'total_items', label: 'الأصناف', format: 'number', tone: 'primary' },
      { key: 'avg_time_seconds', label: 'متوسط الوقت (ث)', format: 'number', tone: 'warning' },
      { key: 'max_time_seconds', label: 'أطول وقت (ث)', format: 'number', tone: 'danger' },
    ],
    sections: [
      {
        id: 'by-station',
        title: 'حسب المحطة',
        extractRows: (p) => reportRows(p, ['by_station']),
        fields: [
          { key: 'station_name', label: 'المحطة', format: 'text', primary: true },
          { key: 'items_count', label: 'الأصناف', format: 'number' },
          { key: 'avg_time_seconds', label: 'متوسط الوقت (ث)', format: 'number' },
        ],
      },
      {
        id: 'top-items',
        title: 'الأصناف الأكثر طلباً',
        extractRows: (p) => reportRows(p, ['top_items']),
        fields: [
          { key: 'product_name', label: 'المنتج', format: 'text', primary: true },
          { key: 'times_ordered', label: 'عدد الطلبات', format: 'number' },
          { key: 'avg_prep_time_seconds', label: 'متوسط التحضير (ث)', format: 'number' },
        ],
      },
    ],
  },
  {
    id: 'operations-offline-sync',
    title: 'مزامنة دون اتصال',
    description: 'طلبات المزامنة وحالاتها',
    group: 'operations',
    icon: 'sync',
    webRoute: '/reports/operations/offline-sync',
    permission: 'view_reports',
    apiMethod: 'offlineSync',
    filters: ['dateRange', 'branch', 'status', 'perPage'],
    paginated: true,
    metrics: [
      { key: 'total_orders', label: 'إجمالي الطلبات', format: 'number', tone: 'info' },
      { key: 'success', label: 'ناجح', format: 'number', tone: 'success' },
      { key: 'pending', label: 'قيد الانتظار', format: 'number', tone: 'warning' },
      { key: 'failed', label: 'فشل', format: 'number', tone: 'danger' },
      { key: 'total_retries', label: 'إعادة المحاولات', format: 'number', tone: 'primary' },
      { key: 'orders_with_retries', label: 'طلبات أعيدت محاولتها', format: 'number', tone: 'warning' },
    ],
    sections: [
      {
        id: 'orders',
        title: 'الطلبات',
        extractRows: (p) => reportRows(p, ['orders']),
        fields: [
          { key: 'client_uuid', label: 'UUID', format: 'text', primary: true },
          { key: 'status', label: 'الحالة', format: 'badge' },
          { key: 'sale_invoice', label: 'الفاتورة', format: 'text' },
          { key: 'retry_count', label: 'إعادة المحاولة', format: 'number' },
          { key: 'error_message', label: 'الخطأ', format: 'text' },
          { key: 'user_name', label: 'المستخدم', format: 'text' },
          { key: 'created_at', label: 'التاريخ', format: 'date' },
        ],
      },
    ],
  },
  {
    id: 'expenses-detail',
    title: 'تفاصيل المصروفات',
    description: 'مصروفات تفصيلية مع المتكرر وحسب التصنيف',
    group: 'finance',
    icon: 'receipt-long',
    webRoute: '/reports/expenses/detail',
    permission: 'view_reports',
    feature: 'advanced_reports',
    apiMethod: 'expensesReport',
    filters: ['dateRange', 'branch', 'perPage'],
    paginated: true,
    metrics: [
      { key: 'total_expenses', label: 'إجمالي المصروفات', format: 'number', tone: 'info' },
      { key: 'total_amount', label: 'إجمالي المبلغ', format: 'money', tone: 'danger' },
      { key: 'active_recurring', label: 'متكرر نشط', format: 'number', tone: 'warning' },
      { key: 'recurring_total', label: 'إجمالي المتكرر', format: 'money', tone: 'primary' },
    ],
    sections: [
      {
        id: 'by-category',
        title: 'حسب التصنيف',
        extractRows: (p) => reportRows(p, ['by_category']),
        fields: [
          { key: 'category_name', label: 'التصنيف', format: 'text', primary: true },
          { key: 'count', label: 'العدد', format: 'number' },
          { key: 'total', label: 'المبلغ', format: 'money' },
        ],
      },
      {
        id: 'expenses',
        title: 'المصروفات',
        extractRows: (p) => reportRows(p, ['expenses']),
        fields: [
          { key: 'description', label: 'الوصف', format: 'text', primary: true },
          { key: 'amount', label: 'المبلغ', format: 'money' },
          { key: 'category_name', label: 'التصنيف', format: 'text' },
          { key: 'reference_number', label: 'المرجع', format: 'text' },
          { key: 'user_name', label: 'بواسطة', format: 'text' },
          { key: 'expense_date', label: 'التاريخ', format: 'date' },
        ],
      },
    ],
  },
];

export function getReportDefinition(id: ReportId): ReportDefinition | undefined {
  return REPORT_DEFINITIONS.find((r) => r.id === id);
}

export function listReportHubItems(): ReportHubItem[] {
  return REPORT_DEFINITIONS.map(({ id, title, description, group, icon, webRoute, permission, feature }) => ({
    id,
    title,
    description,
    group,
    icon,
    webRoute,
    permission,
    feature,
  }));
}
