import { get } from './client';

export const reportsAPI = {
  dailySales: (date?: string) => get('/reports/daily-sales', { date }),
  monthlySales: (month?: string) => get('/reports/monthly-sales', { month }),
  salesRange: (fromDate: string, toDate: string) => get('/reports/sales-range', { from_date: fromDate, to_date: toDate }),
  topProducts: (params?: Record<string, unknown>) => get('/reports/top-products', params),
  lowStock: () => get('/reports/low-stock'),
  topCustomers: (params?: Record<string, unknown>) => get('/reports/top-customers', params),
  profit: (fromDate: string, toDate: string) => get('/reports/profit', { from_date: fromDate, to_date: toDate }),
  debts: () => get('/reports/debts'),
  comprehensiveSales: (params?: Record<string, unknown>) => get('/reports/comprehensive-sales', params),
  comprehensivePurchases: (params?: Record<string, unknown>) => get('/reports/comprehensive-purchases', params),
  products: (params?: Record<string, unknown>) => get('/reports/products', params),
  customers: (params?: Record<string, unknown>) => get('/reports/customers', params),
  suppliers: (params?: Record<string, unknown>) => get('/reports/suppliers', params),
  payments: (params?: Record<string, unknown>) => get('/reports/payments', params),
  inventory: (params?: Record<string, unknown>) => get('/reports/inventory', params),
  inventoryValuation: (params?: Record<string, unknown>) => get('/reports/inventory/valuation', params),
  salesSummary: (params: { branch_id?: string; from_date: string; to_date: string; group_by?: 'product' | 'category' | 'customer' }) => get('/reports/sales/summary', params),
  salesDashboard: (params: { branch_id?: string; from_date: string; to_date: string }) => get('/reports/sales/dashboard', params),
  treasurySummary: (params?: Record<string, unknown>) => get('/reports/treasury/summary', params),
  expensesSummary: (params?: Record<string, unknown>) => get('/reports/expenses/summary', params),
  shiftPerformance: (params?: Record<string, unknown>) => get('/reports/shifts/performance', params),
  refunds: (params?: Record<string, unknown>) => get('/reports/refunds', params),
  tax: (params?: Record<string, unknown>) => get('/reports/tax', params),
  stockMovements: (params?: Record<string, unknown>) => get('/reports/stock-movements', params),
  customerAging: (params?: Record<string, unknown>) => get('/reports/customers/aging', params),
  supplierAging: (params?: Record<string, unknown>) => get('/reports/suppliers/aging', params),
  coupons: (params?: Record<string, unknown>) => get('/reports/coupons', params),
  dining: (params?: Record<string, unknown>) => get('/reports/dining', params),
  delivery: (params?: Record<string, unknown>) => get('/reports/delivery', params),
};
