export const storageKeys = {
  authSession: 'madar.auth.session',
  tenantSlug: 'madar.tenant.slug',
  tenantPrimaryHex: 'madar.tenant.primary_hex',
  activeBranch: 'madar.branch.active',
  branchViewMode: 'madar.branch.view_mode',
  posCatalog: 'madar.pos.catalog',
  posPendingOrders: 'madar.pos.pending_orders',
  posFailedOrders: 'madar.pos.failed_orders',
  offlineQueue: 'madar.offline.queue',
  cachedUser: 'madar.auth.cached_user',
  printerProfiles: 'madar.print.profiles',
  printJobsQueue: 'madar.print.jobs',
  kitchenRoutingRules: 'madar.print.kitchen_routing',
  printDiagnostics: 'madar.print.diagnostics',
};
