export const storageKeys = {
  authSession: 'madar.auth.session',
  tenantSlug: 'madar.tenant.slug',
  tenantPrimaryHex: 'madar.tenant.primary_hex',
  activeBranch: 'madar.branch.active',
  branchViewMode: 'madar.branch.view_mode',
  posCatalog: 'madar.pos.catalog',
  posPendingOrders: 'madar.pos.pending_orders',
  posTableCarts: 'madar.pos.table_carts',
  posLocallyOccupiedTables: 'madar.pos.locally_occupied_tables',
  posFailedOrders: 'madar.pos.failed_orders',
  offlineQueue: 'madar.offline.queue',
  cachedUser: 'madar.auth.cached_user',
  printerProfiles: 'madar.print.profiles',
  printJobsQueue: 'madar.print.jobs',
  kitchenRoutingRules: 'madar.print.kitchen_routing',
  printDiagnostics: 'madar.print.diagnostics',
  heldCartsLocal: 'madar.pos.held_carts_local',
  recentRoutes: 'madar.nav.recent',
  reportsRecent: 'reports_recent',
  offlineTableOps: 'madar.offline.table_ops',
  syncLastSuccessAt: 'madar.sync.last_success_at',
  posSelectedRegisterId: 'madar.pos.selected_register_id',
  posActiveRegisterSessionId: 'madar.pos.active_register_session_id',
  posActiveSessionDrawerFa: 'madar.pos.active_session_drawer_fa',
  posDeviceUuid: 'madar.pos.device_uuid',
};
